/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.c.inflow.domain;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-03-16")
public class DvData implements org.apache.thrift.TBase<DvData, DvData._Fields>, java.io.Serializable, Cloneable, Comparable<DvData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DvData");

  private static final org.apache.thrift.protocol.TField DB_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("dbName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TB_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("tbName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TB_PAR_COL_FIELD_DESC = new org.apache.thrift.protocol.TField("tbParCol", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TB_PAR_COL_VAL_FIELD_DESC = new org.apache.thrift.protocol.TField("tbParColVal", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField TB_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("tbData", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField PROGRESS_FIELD_DESC = new org.apache.thrift.protocol.TField("progress", org.apache.thrift.protocol.TType.I16, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DvDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DvDataTupleSchemeFactory());
  }

  public String dbName; // required
  public String tbName; // required
  public String tbParCol; // required
  public String tbParColVal; // required
  public ByteBuffer tbData; // required
  public short progress; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DB_NAME((short)1, "dbName"),
    TB_NAME((short)2, "tbName"),
    TB_PAR_COL((short)3, "tbParCol"),
    TB_PAR_COL_VAL((short)4, "tbParColVal"),
    TB_DATA((short)5, "tbData"),
    PROGRESS((short)6, "progress");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DB_NAME
          return DB_NAME;
        case 2: // TB_NAME
          return TB_NAME;
        case 3: // TB_PAR_COL
          return TB_PAR_COL;
        case 4: // TB_PAR_COL_VAL
          return TB_PAR_COL_VAL;
        case 5: // TB_DATA
          return TB_DATA;
        case 6: // PROGRESS
          return PROGRESS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROGRESS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DB_NAME, new org.apache.thrift.meta_data.FieldMetaData("dbName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TB_NAME, new org.apache.thrift.meta_data.FieldMetaData("tbName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TB_PAR_COL, new org.apache.thrift.meta_data.FieldMetaData("tbParCol", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TB_PAR_COL_VAL, new org.apache.thrift.meta_data.FieldMetaData("tbParColVal", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TB_DATA, new org.apache.thrift.meta_data.FieldMetaData("tbData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.PROGRESS, new org.apache.thrift.meta_data.FieldMetaData("progress", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DvData.class, metaDataMap);
  }

  public DvData() {
  }

  public DvData(
    String dbName,
    String tbName,
    String tbParCol,
    String tbParColVal,
    ByteBuffer tbData,
    short progress)
  {
    this();
    this.dbName = dbName;
    this.tbName = tbName;
    this.tbParCol = tbParCol;
    this.tbParColVal = tbParColVal;
    this.tbData = org.apache.thrift.TBaseHelper.copyBinary(tbData);
    this.progress = progress;
    setProgressIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DvData(DvData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDbName()) {
      this.dbName = other.dbName;
    }
    if (other.isSetTbName()) {
      this.tbName = other.tbName;
    }
    if (other.isSetTbParCol()) {
      this.tbParCol = other.tbParCol;
    }
    if (other.isSetTbParColVal()) {
      this.tbParColVal = other.tbParColVal;
    }
    if (other.isSetTbData()) {
      this.tbData = org.apache.thrift.TBaseHelper.copyBinary(other.tbData);
    }
    this.progress = other.progress;
  }

  public DvData deepCopy() {
    return new DvData(this);
  }

  @Override
  public void clear() {
    this.dbName = null;
    this.tbName = null;
    this.tbParCol = null;
    this.tbParColVal = null;
    this.tbData = null;
    setProgressIsSet(false);
    this.progress = 0;
  }

  public String getDbName() {
    return this.dbName;
  }

  public DvData setDbName(String dbName) {
    this.dbName = dbName;
    return this;
  }

  public void unsetDbName() {
    this.dbName = null;
  }

  /** Returns true if field dbName is set (has been assigned a value) and false otherwise */
  public boolean isSetDbName() {
    return this.dbName != null;
  }

  public void setDbNameIsSet(boolean value) {
    if (!value) {
      this.dbName = null;
    }
  }

  public String getTbName() {
    return this.tbName;
  }

  public DvData setTbName(String tbName) {
    this.tbName = tbName;
    return this;
  }

  public void unsetTbName() {
    this.tbName = null;
  }

  /** Returns true if field tbName is set (has been assigned a value) and false otherwise */
  public boolean isSetTbName() {
    return this.tbName != null;
  }

  public void setTbNameIsSet(boolean value) {
    if (!value) {
      this.tbName = null;
    }
  }

  public String getTbParCol() {
    return this.tbParCol;
  }

  public DvData setTbParCol(String tbParCol) {
    this.tbParCol = tbParCol;
    return this;
  }

  public void unsetTbParCol() {
    this.tbParCol = null;
  }

  /** Returns true if field tbParCol is set (has been assigned a value) and false otherwise */
  public boolean isSetTbParCol() {
    return this.tbParCol != null;
  }

  public void setTbParColIsSet(boolean value) {
    if (!value) {
      this.tbParCol = null;
    }
  }

  public String getTbParColVal() {
    return this.tbParColVal;
  }

  public DvData setTbParColVal(String tbParColVal) {
    this.tbParColVal = tbParColVal;
    return this;
  }

  public void unsetTbParColVal() {
    this.tbParColVal = null;
  }

  /** Returns true if field tbParColVal is set (has been assigned a value) and false otherwise */
  public boolean isSetTbParColVal() {
    return this.tbParColVal != null;
  }

  public void setTbParColValIsSet(boolean value) {
    if (!value) {
      this.tbParColVal = null;
    }
  }

  public byte[] getTbData() {
    setTbData(org.apache.thrift.TBaseHelper.rightSize(tbData));
    return tbData == null ? null : tbData.array();
  }

  public ByteBuffer bufferForTbData() {
    return org.apache.thrift.TBaseHelper.copyBinary(tbData);
  }

  public DvData setTbData(byte[] tbData) {
    this.tbData = tbData == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(tbData, tbData.length));
    return this;
  }

  public DvData setTbData(ByteBuffer tbData) {
    this.tbData = org.apache.thrift.TBaseHelper.copyBinary(tbData);
    return this;
  }

  public void unsetTbData() {
    this.tbData = null;
  }

  /** Returns true if field tbData is set (has been assigned a value) and false otherwise */
  public boolean isSetTbData() {
    return this.tbData != null;
  }

  public void setTbDataIsSet(boolean value) {
    if (!value) {
      this.tbData = null;
    }
  }

  public short getProgress() {
    return this.progress;
  }

  public DvData setProgress(short progress) {
    this.progress = progress;
    setProgressIsSet(true);
    return this;
  }

  public void unsetProgress() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PROGRESS_ISSET_ID);
  }

  /** Returns true if field progress is set (has been assigned a value) and false otherwise */
  public boolean isSetProgress() {
    return EncodingUtils.testBit(__isset_bitfield, __PROGRESS_ISSET_ID);
  }

  public void setProgressIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PROGRESS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DB_NAME:
      if (value == null) {
        unsetDbName();
      } else {
        setDbName((String)value);
      }
      break;

    case TB_NAME:
      if (value == null) {
        unsetTbName();
      } else {
        setTbName((String)value);
      }
      break;

    case TB_PAR_COL:
      if (value == null) {
        unsetTbParCol();
      } else {
        setTbParCol((String)value);
      }
      break;

    case TB_PAR_COL_VAL:
      if (value == null) {
        unsetTbParColVal();
      } else {
        setTbParColVal((String)value);
      }
      break;

    case TB_DATA:
      if (value == null) {
        unsetTbData();
      } else {
        setTbData((ByteBuffer)value);
      }
      break;

    case PROGRESS:
      if (value == null) {
        unsetProgress();
      } else {
        setProgress((Short)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DB_NAME:
      return getDbName();

    case TB_NAME:
      return getTbName();

    case TB_PAR_COL:
      return getTbParCol();

    case TB_PAR_COL_VAL:
      return getTbParColVal();

    case TB_DATA:
      return getTbData();

    case PROGRESS:
      return getProgress();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DB_NAME:
      return isSetDbName();
    case TB_NAME:
      return isSetTbName();
    case TB_PAR_COL:
      return isSetTbParCol();
    case TB_PAR_COL_VAL:
      return isSetTbParColVal();
    case TB_DATA:
      return isSetTbData();
    case PROGRESS:
      return isSetProgress();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DvData)
      return this.equals((DvData)that);
    return false;
  }

  public boolean equals(DvData that) {
    if (that == null)
      return false;

    boolean this_present_dbName = true && this.isSetDbName();
    boolean that_present_dbName = true && that.isSetDbName();
    if (this_present_dbName || that_present_dbName) {
      if (!(this_present_dbName && that_present_dbName))
        return false;
      if (!this.dbName.equals(that.dbName))
        return false;
    }

    boolean this_present_tbName = true && this.isSetTbName();
    boolean that_present_tbName = true && that.isSetTbName();
    if (this_present_tbName || that_present_tbName) {
      if (!(this_present_tbName && that_present_tbName))
        return false;
      if (!this.tbName.equals(that.tbName))
        return false;
    }

    boolean this_present_tbParCol = true && this.isSetTbParCol();
    boolean that_present_tbParCol = true && that.isSetTbParCol();
    if (this_present_tbParCol || that_present_tbParCol) {
      if (!(this_present_tbParCol && that_present_tbParCol))
        return false;
      if (!this.tbParCol.equals(that.tbParCol))
        return false;
    }

    boolean this_present_tbParColVal = true && this.isSetTbParColVal();
    boolean that_present_tbParColVal = true && that.isSetTbParColVal();
    if (this_present_tbParColVal || that_present_tbParColVal) {
      if (!(this_present_tbParColVal && that_present_tbParColVal))
        return false;
      if (!this.tbParColVal.equals(that.tbParColVal))
        return false;
    }

    boolean this_present_tbData = true && this.isSetTbData();
    boolean that_present_tbData = true && that.isSetTbData();
    if (this_present_tbData || that_present_tbData) {
      if (!(this_present_tbData && that_present_tbData))
        return false;
      if (!this.tbData.equals(that.tbData))
        return false;
    }

    boolean this_present_progress = true;
    boolean that_present_progress = true;
    if (this_present_progress || that_present_progress) {
      if (!(this_present_progress && that_present_progress))
        return false;
      if (this.progress != that.progress)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_dbName = true && (isSetDbName());
    list.add(present_dbName);
    if (present_dbName)
      list.add(dbName);

    boolean present_tbName = true && (isSetTbName());
    list.add(present_tbName);
    if (present_tbName)
      list.add(tbName);

    boolean present_tbParCol = true && (isSetTbParCol());
    list.add(present_tbParCol);
    if (present_tbParCol)
      list.add(tbParCol);

    boolean present_tbParColVal = true && (isSetTbParColVal());
    list.add(present_tbParColVal);
    if (present_tbParColVal)
      list.add(tbParColVal);

    boolean present_tbData = true && (isSetTbData());
    list.add(present_tbData);
    if (present_tbData)
      list.add(tbData);

    boolean present_progress = true;
    list.add(present_progress);
    if (present_progress)
      list.add(progress);

    return list.hashCode();
  }

  @Override
  public int compareTo(DvData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDbName()).compareTo(other.isSetDbName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDbName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dbName, other.dbName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTbName()).compareTo(other.isSetTbName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTbName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tbName, other.tbName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTbParCol()).compareTo(other.isSetTbParCol());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTbParCol()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tbParCol, other.tbParCol);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTbParColVal()).compareTo(other.isSetTbParColVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTbParColVal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tbParColVal, other.tbParColVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTbData()).compareTo(other.isSetTbData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTbData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tbData, other.tbData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProgress()).compareTo(other.isSetProgress());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProgress()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.progress, other.progress);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DvData(");
    boolean first = true;

    sb.append("dbName:");
    if (this.dbName == null) {
      sb.append("null");
    } else {
      sb.append(this.dbName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tbName:");
    if (this.tbName == null) {
      sb.append("null");
    } else {
      sb.append(this.tbName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tbParCol:");
    if (this.tbParCol == null) {
      sb.append("null");
    } else {
      sb.append(this.tbParCol);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tbParColVal:");
    if (this.tbParColVal == null) {
      sb.append("null");
    } else {
      sb.append(this.tbParColVal);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tbData:");
    if (this.tbData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.tbData, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("progress:");
    sb.append(this.progress);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DvDataStandardSchemeFactory implements SchemeFactory {
    public DvDataStandardScheme getScheme() {
      return new DvDataStandardScheme();
    }
  }

  private static class DvDataStandardScheme extends StandardScheme<DvData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DvData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DB_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dbName = iprot.readString();
              struct.setDbNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TB_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tbName = iprot.readString();
              struct.setTbNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TB_PAR_COL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tbParCol = iprot.readString();
              struct.setTbParColIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TB_PAR_COL_VAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tbParColVal = iprot.readString();
              struct.setTbParColValIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TB_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tbData = iprot.readBinary();
              struct.setTbDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // PROGRESS
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.progress = iprot.readI16();
              struct.setProgressIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DvData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dbName != null) {
        oprot.writeFieldBegin(DB_NAME_FIELD_DESC);
        oprot.writeString(struct.dbName);
        oprot.writeFieldEnd();
      }
      if (struct.tbName != null) {
        oprot.writeFieldBegin(TB_NAME_FIELD_DESC);
        oprot.writeString(struct.tbName);
        oprot.writeFieldEnd();
      }
      if (struct.tbParCol != null) {
        oprot.writeFieldBegin(TB_PAR_COL_FIELD_DESC);
        oprot.writeString(struct.tbParCol);
        oprot.writeFieldEnd();
      }
      if (struct.tbParColVal != null) {
        oprot.writeFieldBegin(TB_PAR_COL_VAL_FIELD_DESC);
        oprot.writeString(struct.tbParColVal);
        oprot.writeFieldEnd();
      }
      if (struct.tbData != null) {
        oprot.writeFieldBegin(TB_DATA_FIELD_DESC);
        oprot.writeBinary(struct.tbData);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PROGRESS_FIELD_DESC);
      oprot.writeI16(struct.progress);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DvDataTupleSchemeFactory implements SchemeFactory {
    public DvDataTupleScheme getScheme() {
      return new DvDataTupleScheme();
    }
  }

  private static class DvDataTupleScheme extends TupleScheme<DvData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DvData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDbName()) {
        optionals.set(0);
      }
      if (struct.isSetTbName()) {
        optionals.set(1);
      }
      if (struct.isSetTbParCol()) {
        optionals.set(2);
      }
      if (struct.isSetTbParColVal()) {
        optionals.set(3);
      }
      if (struct.isSetTbData()) {
        optionals.set(4);
      }
      if (struct.isSetProgress()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetDbName()) {
        oprot.writeString(struct.dbName);
      }
      if (struct.isSetTbName()) {
        oprot.writeString(struct.tbName);
      }
      if (struct.isSetTbParCol()) {
        oprot.writeString(struct.tbParCol);
      }
      if (struct.isSetTbParColVal()) {
        oprot.writeString(struct.tbParColVal);
      }
      if (struct.isSetTbData()) {
        oprot.writeBinary(struct.tbData);
      }
      if (struct.isSetProgress()) {
        oprot.writeI16(struct.progress);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DvData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.dbName = iprot.readString();
        struct.setDbNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.tbName = iprot.readString();
        struct.setTbNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.tbParCol = iprot.readString();
        struct.setTbParColIsSet(true);
      }
      if (incoming.get(3)) {
        struct.tbParColVal = iprot.readString();
        struct.setTbParColValIsSet(true);
      }
      if (incoming.get(4)) {
        struct.tbData = iprot.readBinary();
        struct.setTbDataIsSet(true);
      }
      if (incoming.get(5)) {
        struct.progress = iprot.readI16();
        struct.setProgressIsSet(true);
      }
    }
  }

}

