/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.c.inflow.domain;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-27")
public class RoleCreateInfo implements org.apache.thrift.TBase<RoleCreateInfo, RoleCreateInfo._Fields>, java.io.Serializable, Cloneable, Comparable<RoleCreateInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RoleCreateInfo");

  private static final org.apache.thrift.protocol.TField ROLE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("roleId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ROLE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("roleType", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ROLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("roleName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ROLE_GENDER_FIELD_DESC = new org.apache.thrift.protocol.TField("roleGender", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField ROLE_AGE_FIELD_DESC = new org.apache.thrift.protocol.TField("roleAge", org.apache.thrift.protocol.TType.I16, (short)5);
  private static final org.apache.thrift.protocol.TField ROLE_LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("roleLevel", org.apache.thrift.protocol.TType.I16, (short)6);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RoleCreateInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RoleCreateInfoTupleSchemeFactory());
  }

  public String roleId; // required
  public String roleType; // required
  public String roleName; // required
  public String roleGender; // required
  public short roleAge; // required
  public short roleLevel; // required
  public long createTime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ROLE_ID((short)1, "roleId"),
    ROLE_TYPE((short)2, "roleType"),
    ROLE_NAME((short)3, "roleName"),
    ROLE_GENDER((short)4, "roleGender"),
    ROLE_AGE((short)5, "roleAge"),
    ROLE_LEVEL((short)6, "roleLevel"),
    CREATE_TIME((short)7, "createTime");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ROLE_ID
          return ROLE_ID;
        case 2: // ROLE_TYPE
          return ROLE_TYPE;
        case 3: // ROLE_NAME
          return ROLE_NAME;
        case 4: // ROLE_GENDER
          return ROLE_GENDER;
        case 5: // ROLE_AGE
          return ROLE_AGE;
        case 6: // ROLE_LEVEL
          return ROLE_LEVEL;
        case 7: // CREATE_TIME
          return CREATE_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ROLEAGE_ISSET_ID = 0;
  private static final int __ROLELEVEL_ISSET_ID = 1;
  private static final int __CREATETIME_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ROLE_ID, new org.apache.thrift.meta_data.FieldMetaData("roleId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROLE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("roleType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("roleName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROLE_GENDER, new org.apache.thrift.meta_data.FieldMetaData("roleGender", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROLE_AGE, new org.apache.thrift.meta_data.FieldMetaData("roleAge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16        , "int16")));
    tmpMap.put(_Fields.ROLE_LEVEL, new org.apache.thrift.meta_data.FieldMetaData("roleLevel", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16        , "int16")));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "int64")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RoleCreateInfo.class, metaDataMap);
  }

  public RoleCreateInfo() {
  }

  public RoleCreateInfo(
    String roleId,
    String roleType,
    String roleName,
    String roleGender,
    short roleAge,
    short roleLevel,
    long createTime)
  {
    this();
    this.roleId = roleId;
    this.roleType = roleType;
    this.roleName = roleName;
    this.roleGender = roleGender;
    this.roleAge = roleAge;
    setRoleAgeIsSet(true);
    this.roleLevel = roleLevel;
    setRoleLevelIsSet(true);
    this.createTime = createTime;
    setCreateTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RoleCreateInfo(RoleCreateInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetRoleId()) {
      this.roleId = other.roleId;
    }
    if (other.isSetRoleType()) {
      this.roleType = other.roleType;
    }
    if (other.isSetRoleName()) {
      this.roleName = other.roleName;
    }
    if (other.isSetRoleGender()) {
      this.roleGender = other.roleGender;
    }
    this.roleAge = other.roleAge;
    this.roleLevel = other.roleLevel;
    this.createTime = other.createTime;
  }

  public RoleCreateInfo deepCopy() {
    return new RoleCreateInfo(this);
  }

  @Override
  public void clear() {
    this.roleId = null;
    this.roleType = null;
    this.roleName = null;
    this.roleGender = null;
    setRoleAgeIsSet(false);
    this.roleAge = 0;
    setRoleLevelIsSet(false);
    this.roleLevel = 0;
    setCreateTimeIsSet(false);
    this.createTime = 0;
  }

  public String getRoleId() {
    return this.roleId;
  }

  public RoleCreateInfo setRoleId(String roleId) {
    this.roleId = roleId;
    return this;
  }

  public void unsetRoleId() {
    this.roleId = null;
  }

  /** Returns true if field roleId is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleId() {
    return this.roleId != null;
  }

  public void setRoleIdIsSet(boolean value) {
    if (!value) {
      this.roleId = null;
    }
  }

  public String getRoleType() {
    return this.roleType;
  }

  public RoleCreateInfo setRoleType(String roleType) {
    this.roleType = roleType;
    return this;
  }

  public void unsetRoleType() {
    this.roleType = null;
  }

  /** Returns true if field roleType is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleType() {
    return this.roleType != null;
  }

  public void setRoleTypeIsSet(boolean value) {
    if (!value) {
      this.roleType = null;
    }
  }

  public String getRoleName() {
    return this.roleName;
  }

  public RoleCreateInfo setRoleName(String roleName) {
    this.roleName = roleName;
    return this;
  }

  public void unsetRoleName() {
    this.roleName = null;
  }

  /** Returns true if field roleName is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleName() {
    return this.roleName != null;
  }

  public void setRoleNameIsSet(boolean value) {
    if (!value) {
      this.roleName = null;
    }
  }

  public String getRoleGender() {
    return this.roleGender;
  }

  public RoleCreateInfo setRoleGender(String roleGender) {
    this.roleGender = roleGender;
    return this;
  }

  public void unsetRoleGender() {
    this.roleGender = null;
  }

  /** Returns true if field roleGender is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleGender() {
    return this.roleGender != null;
  }

  public void setRoleGenderIsSet(boolean value) {
    if (!value) {
      this.roleGender = null;
    }
  }

  public short getRoleAge() {
    return this.roleAge;
  }

  public RoleCreateInfo setRoleAge(short roleAge) {
    this.roleAge = roleAge;
    setRoleAgeIsSet(true);
    return this;
  }

  public void unsetRoleAge() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ROLEAGE_ISSET_ID);
  }

  /** Returns true if field roleAge is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleAge() {
    return EncodingUtils.testBit(__isset_bitfield, __ROLEAGE_ISSET_ID);
  }

  public void setRoleAgeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ROLEAGE_ISSET_ID, value);
  }

  public short getRoleLevel() {
    return this.roleLevel;
  }

  public RoleCreateInfo setRoleLevel(short roleLevel) {
    this.roleLevel = roleLevel;
    setRoleLevelIsSet(true);
    return this;
  }

  public void unsetRoleLevel() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ROLELEVEL_ISSET_ID);
  }

  /** Returns true if field roleLevel is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleLevel() {
    return EncodingUtils.testBit(__isset_bitfield, __ROLELEVEL_ISSET_ID);
  }

  public void setRoleLevelIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ROLELEVEL_ISSET_ID, value);
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public RoleCreateInfo setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ROLE_ID:
      if (value == null) {
        unsetRoleId();
      } else {
        setRoleId((String)value);
      }
      break;

    case ROLE_TYPE:
      if (value == null) {
        unsetRoleType();
      } else {
        setRoleType((String)value);
      }
      break;

    case ROLE_NAME:
      if (value == null) {
        unsetRoleName();
      } else {
        setRoleName((String)value);
      }
      break;

    case ROLE_GENDER:
      if (value == null) {
        unsetRoleGender();
      } else {
        setRoleGender((String)value);
      }
      break;

    case ROLE_AGE:
      if (value == null) {
        unsetRoleAge();
      } else {
        setRoleAge((Short)value);
      }
      break;

    case ROLE_LEVEL:
      if (value == null) {
        unsetRoleLevel();
      } else {
        setRoleLevel((Short)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ROLE_ID:
      return getRoleId();

    case ROLE_TYPE:
      return getRoleType();

    case ROLE_NAME:
      return getRoleName();

    case ROLE_GENDER:
      return getRoleGender();

    case ROLE_AGE:
      return getRoleAge();

    case ROLE_LEVEL:
      return getRoleLevel();

    case CREATE_TIME:
      return getCreateTime();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ROLE_ID:
      return isSetRoleId();
    case ROLE_TYPE:
      return isSetRoleType();
    case ROLE_NAME:
      return isSetRoleName();
    case ROLE_GENDER:
      return isSetRoleGender();
    case ROLE_AGE:
      return isSetRoleAge();
    case ROLE_LEVEL:
      return isSetRoleLevel();
    case CREATE_TIME:
      return isSetCreateTime();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RoleCreateInfo)
      return this.equals((RoleCreateInfo)that);
    return false;
  }

  public boolean equals(RoleCreateInfo that) {
    if (that == null)
      return false;

    boolean this_present_roleId = true && this.isSetRoleId();
    boolean that_present_roleId = true && that.isSetRoleId();
    if (this_present_roleId || that_present_roleId) {
      if (!(this_present_roleId && that_present_roleId))
        return false;
      if (!this.roleId.equals(that.roleId))
        return false;
    }

    boolean this_present_roleType = true && this.isSetRoleType();
    boolean that_present_roleType = true && that.isSetRoleType();
    if (this_present_roleType || that_present_roleType) {
      if (!(this_present_roleType && that_present_roleType))
        return false;
      if (!this.roleType.equals(that.roleType))
        return false;
    }

    boolean this_present_roleName = true && this.isSetRoleName();
    boolean that_present_roleName = true && that.isSetRoleName();
    if (this_present_roleName || that_present_roleName) {
      if (!(this_present_roleName && that_present_roleName))
        return false;
      if (!this.roleName.equals(that.roleName))
        return false;
    }

    boolean this_present_roleGender = true && this.isSetRoleGender();
    boolean that_present_roleGender = true && that.isSetRoleGender();
    if (this_present_roleGender || that_present_roleGender) {
      if (!(this_present_roleGender && that_present_roleGender))
        return false;
      if (!this.roleGender.equals(that.roleGender))
        return false;
    }

    boolean this_present_roleAge = true;
    boolean that_present_roleAge = true;
    if (this_present_roleAge || that_present_roleAge) {
      if (!(this_present_roleAge && that_present_roleAge))
        return false;
      if (this.roleAge != that.roleAge)
        return false;
    }

    boolean this_present_roleLevel = true;
    boolean that_present_roleLevel = true;
    if (this_present_roleLevel || that_present_roleLevel) {
      if (!(this_present_roleLevel && that_present_roleLevel))
        return false;
      if (this.roleLevel != that.roleLevel)
        return false;
    }

    boolean this_present_createTime = true;
    boolean that_present_createTime = true;
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_roleId = true && (isSetRoleId());
    list.add(present_roleId);
    if (present_roleId)
      list.add(roleId);

    boolean present_roleType = true && (isSetRoleType());
    list.add(present_roleType);
    if (present_roleType)
      list.add(roleType);

    boolean present_roleName = true && (isSetRoleName());
    list.add(present_roleName);
    if (present_roleName)
      list.add(roleName);

    boolean present_roleGender = true && (isSetRoleGender());
    list.add(present_roleGender);
    if (present_roleGender)
      list.add(roleGender);

    boolean present_roleAge = true;
    list.add(present_roleAge);
    if (present_roleAge)
      list.add(roleAge);

    boolean present_roleLevel = true;
    list.add(present_roleLevel);
    if (present_roleLevel)
      list.add(roleLevel);

    boolean present_createTime = true;
    list.add(present_createTime);
    if (present_createTime)
      list.add(createTime);

    return list.hashCode();
  }

  @Override
  public int compareTo(RoleCreateInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRoleId()).compareTo(other.isSetRoleId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleId, other.roleId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRoleType()).compareTo(other.isSetRoleType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleType, other.roleType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRoleName()).compareTo(other.isSetRoleName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleName, other.roleName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRoleGender()).compareTo(other.isSetRoleGender());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleGender()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleGender, other.roleGender);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRoleAge()).compareTo(other.isSetRoleAge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleAge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleAge, other.roleAge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRoleLevel()).compareTo(other.isSetRoleLevel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleLevel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleLevel, other.roleLevel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTime()).compareTo(other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RoleCreateInfo(");
    boolean first = true;

    sb.append("roleId:");
    if (this.roleId == null) {
      sb.append("null");
    } else {
      sb.append(this.roleId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("roleType:");
    if (this.roleType == null) {
      sb.append("null");
    } else {
      sb.append(this.roleType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("roleName:");
    if (this.roleName == null) {
      sb.append("null");
    } else {
      sb.append(this.roleName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("roleGender:");
    if (this.roleGender == null) {
      sb.append("null");
    } else {
      sb.append(this.roleGender);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("roleAge:");
    sb.append(this.roleAge);
    first = false;
    if (!first) sb.append(", ");
    sb.append("roleLevel:");
    sb.append(this.roleLevel);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createTime:");
    sb.append(this.createTime);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RoleCreateInfoStandardSchemeFactory implements SchemeFactory {
    public RoleCreateInfoStandardScheme getScheme() {
      return new RoleCreateInfoStandardScheme();
    }
  }

  private static class RoleCreateInfoStandardScheme extends StandardScheme<RoleCreateInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RoleCreateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ROLE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.roleId = iprot.readString();
              struct.setRoleIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ROLE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.roleType = iprot.readString();
              struct.setRoleTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ROLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.roleName = iprot.readString();
              struct.setRoleNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ROLE_GENDER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.roleGender = iprot.readString();
              struct.setRoleGenderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ROLE_AGE
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.roleAge = iprot.readI16();
              struct.setRoleAgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ROLE_LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.roleLevel = iprot.readI16();
              struct.setRoleLevelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RoleCreateInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.roleId != null) {
        oprot.writeFieldBegin(ROLE_ID_FIELD_DESC);
        oprot.writeString(struct.roleId);
        oprot.writeFieldEnd();
      }
      if (struct.roleType != null) {
        oprot.writeFieldBegin(ROLE_TYPE_FIELD_DESC);
        oprot.writeString(struct.roleType);
        oprot.writeFieldEnd();
      }
      if (struct.roleName != null) {
        oprot.writeFieldBegin(ROLE_NAME_FIELD_DESC);
        oprot.writeString(struct.roleName);
        oprot.writeFieldEnd();
      }
      if (struct.roleGender != null) {
        oprot.writeFieldBegin(ROLE_GENDER_FIELD_DESC);
        oprot.writeString(struct.roleGender);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ROLE_AGE_FIELD_DESC);
      oprot.writeI16(struct.roleAge);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ROLE_LEVEL_FIELD_DESC);
      oprot.writeI16(struct.roleLevel);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.createTime);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RoleCreateInfoTupleSchemeFactory implements SchemeFactory {
    public RoleCreateInfoTupleScheme getScheme() {
      return new RoleCreateInfoTupleScheme();
    }
  }

  private static class RoleCreateInfoTupleScheme extends TupleScheme<RoleCreateInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RoleCreateInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRoleId()) {
        optionals.set(0);
      }
      if (struct.isSetRoleType()) {
        optionals.set(1);
      }
      if (struct.isSetRoleName()) {
        optionals.set(2);
      }
      if (struct.isSetRoleGender()) {
        optionals.set(3);
      }
      if (struct.isSetRoleAge()) {
        optionals.set(4);
      }
      if (struct.isSetRoleLevel()) {
        optionals.set(5);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetRoleId()) {
        oprot.writeString(struct.roleId);
      }
      if (struct.isSetRoleType()) {
        oprot.writeString(struct.roleType);
      }
      if (struct.isSetRoleName()) {
        oprot.writeString(struct.roleName);
      }
      if (struct.isSetRoleGender()) {
        oprot.writeString(struct.roleGender);
      }
      if (struct.isSetRoleAge()) {
        oprot.writeI16(struct.roleAge);
      }
      if (struct.isSetRoleLevel()) {
        oprot.writeI16(struct.roleLevel);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RoleCreateInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.roleId = iprot.readString();
        struct.setRoleIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.roleType = iprot.readString();
        struct.setRoleTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.roleName = iprot.readString();
        struct.setRoleNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.roleGender = iprot.readString();
        struct.setRoleGenderIsSet(true);
      }
      if (incoming.get(4)) {
        struct.roleAge = iprot.readI16();
        struct.setRoleAgeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.roleLevel = iprot.readI16();
        struct.setRoleLevelIsSet(true);
      }
      if (incoming.get(6)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
    }
  }

}

